# Generated by Django 4.2.2 on 2025-04-19 18:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("catalog", "0004_alter_product_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="owner",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="имя владельца",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="publication",
            field=models.BooleanField(default=False, verbose_name="Статус публикации"),
        ),
    ]
